spring.application.name=stolat
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.thymeleaf.check-template-location=false

# Logging
logging.level.org.jaudiotagger=WARN

# API
stolat.user-agent=StoLat/0.1.5-SNAPSHOT (https://github.com/guisil/stolat)

# Notification
stolat.notification.from=StoLat <stolat@noreply.com>
stolat.notification.cron=0 0 8 * * *
