DROP TRIGGER trigger_call_remove_album_birthday_for_artist ON artist;

DROP FUNCTION call_remove_album_birthday_for_artist;

DROP TRIGGER trigger_call_remove_album_birthday_for_release_group ON release_group;

DROP FUNCTION call_remove_album_birthday_for_release_group;

DROP TRIGGER trigger_call_upsert_album_birthday_unknown_country ON release_unknown_country;

DROP TRIGGER trigger_call_upsert_album_birthday_country ON release_country;

DROP FUNCTION call_upsert_album_birthday;

DROP FUNCTION upsert_album_birthday;